// <auto-generated />
using System;
using Kassen.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kassen.Migrations
{
    [DbContext(typeof(KassenContext))]
    [Migration("20240623152540_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Kassen.Games.Jackpot", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Jackpot");
                });

            modelBuilder.Entity("Kassen.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDrinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isInRaffle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
