// <auto-generated />
using System;
using Kassen.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kassen.Migrations
{
    [DbContext(typeof(KassenContext))]
    [Migration("20240623153758_DrinkingBuddy")]
    partial class DrinkingBuddy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Kassen.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDrinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isInRaffle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Models.DrinkingBuddy", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuckedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuckerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("FuckedName");

                    b.HasIndex("FuckerName");

                    b.ToTable("DrinkingBuddy");
                });

            modelBuilder.Entity("Models.DrinkingBuddy", b =>
                {
                    b.HasOne("Kassen.Models.Player", "Fucked")
                        .WithMany()
                        .HasForeignKey("FuckedName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kassen.Models.Player", "Fucker")
                        .WithMany()
                        .HasForeignKey("FuckerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fucked");

                    b.Navigation("Fucker");
                });
#pragma warning restore 612, 618
        }
    }
}
